version: '3.9'

services:
  rust-axum-performance:
    image: rust:1.83.0
    restart: always
    container_name: rust-axum-performance
    ports:
      - "8080:3000"
    command:
      - bash
      - -c
      - >
        apt-get update &&
        apt-get install -y git build-essential libssl-dev pkg-config &&
        mkdir -p /app/repo &&
        git clone https://github.com/dmarcosl/rust-axum-performance /app/repo || true &&
        cd /app/repo &&
        cargo build --release &&
        cargo run --release;

  java-webclient-performance:
    image: openjdk:21-jdk-slim
    restart: always
    container_name: java-webclient-performance
    ports:
      - "8081:8080"
    command:
      - bash
      - -c
      - >
        apt-get update &&
        apt-get install -y git maven &&
        mkdir -p /app/repo &&
        git clone https://github.com/dmarcosl/java-webclient-performance /app/repo || true &&
        cd /app/repo &&
        mvn clean package &&
        java -jar boot/target/performance-boot-0.0.1-SNAPSHOT.jar;

  java-restclient-performance:
    image: openjdk:21-jdk-slim
    restart: always
    container_name: java-restclient-performance
    ports:
      - "8082:8080"
    command:
      - bash
      - -c
      - >
        apt-get update &&
        apt-get install -y git maven &&
        mkdir -p /app/repo &&
        git clone https://github.com/dmarcosl/java-restclient-performance /app/repo || true &&
        cd /app/repo &&
        mvn clean package &&
        java -jar boot/target/performance-boot-0.0.1-SNAPSHOT.jar;

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

  k6:
    image: grafana/k6:latest
    container_name: k6
    entrypoint: [ "/bin/sh", "-c" ]
    command: [ "k6 run --out influxdb=http://influxdb:8086 /scripts/main.js" ]
    volumes:
      - ./k6:/scripts
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    depends_on:
      - grafana
